---
# tasks file for hswong3i.ufw

- name: apt-get install
  apt:
    name="{{ item }}"
    state=latest
  with_items:
    - ufw
  notify: reload ufw
  tags: hswong3i.ufw

- name: set state
  ufw: state={{ ufw_state }}
  notify: reload ufw
  tags: hswong3i.ufw

- name: enable logging
  ufw: logging={{ ufw_logging }}
  notify: reload ufw
  tags: hswong3i.ufw

- name: setup policy per direction
  ufw:
    direction={{ item.direction }}
    policy={{ item.policy }}
  with_items:
    - "{{ ufw_direction }}"
  notify: reload ufw
  tags: hswong3i.ufw

- name: setup rule per interface
  ufw:
    interface={{ item.interface }}
    direction={{ item.direction }}
    rule={{ item.rule }}
  with_items:
    - "{{ ufw_interface }}"
  notify: reload ufw
  tags: hswong3i.ufw

- name: setup rule per from_ip
  ufw:
    from_ip={{ item.from_ip }}
    rule={{ item.rule }}
  with_items:
    - "{{ ufw_from_ip }}"
  notify: reload ufw
  tags: hswong3i.ufw

- name: setup rule per to_port
  ufw:
    to_port={{ item.to_port }}
    proto={{ item.proto }}
    rule={{ item.rule }}
  with_items:
    - "{{ ufw_to_port }}"
  notify: reload ufw
  tags: hswong3i.ufw

- name: setup rule per route
  shell: ufw {{ 'route' if item.route }} {{ item.rule }} proto {{ item.proto }} from {{ item.from_ip }} port {{ item.from_port }} to {{ item.to_ip }} port {{ item.to_port }}
  with_items:
    - "{{ ufw_route }}"
  notify: reload ufw
  tags: hswong3i.ufw
